### PR TITLE
Proposal: Add Set.fullOuterJoin! 🈴

### PR DESCRIPTION
**Pull request by kutyel**
I know this is just a combination of `union + diff` but maybe it will be useful for someone else? 🤞🏻 

image

### CODE REVIEW

**Comment by turboMaCk** [comment]
I think this will be though one. As far as I know set theory doesn't describe this type of binary operations and Sets are well sets. I don't think this relational naming in particular is helpful. I think perhaps even `xor` would be the better name when it comes to it. The trouble is how to name this in a way it fits to overall naming conventions.

**Comment by kutyel** [comment]
So should I just rename it to `xor`? 🤔

**Comment by turboMaCk** [comment]
can you maybe check if some other libraries (non elm) implementing sets provide function like this and how do they name it? I would first check fp languages but anything can help us here.

**Comment by kutyel** [comment]
@turboMaCk renamed to `symDifference` and tried to improve the docs a little bit 😉

**Comment by kutyel** [comment]
Adding the Twitter discussion here for completion and kudos to @anilamar https://twitter.com/FlavioCorpa/status/1486823276718481408?s=20&t=1WuZ5CULdLw2QZiU5_tYsg

**Pull request merged**
